server:
  shutdown: graceful
  port: 8181
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /portal/api
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  error:
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RedisStudy?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: "SELECT 1"
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100